version: '3.8'
services:
  app:
    build: .
    container_name: taskflow
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - database
    
  database:
    image: mysql:8.0
    container_name: taskflow-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: